language: python
matrix:
  include:
  - env: TOX_ENV=py27
  - env: TOX_ENV=py34
  - env: TOX_ENV=py35
  - env: TOX_ENV=pypy
  - env: TOX_ENV=pep8
  - env: TOX_ENV=pylint
  - env: TOX_ENV=coverage

# commands to install dependencies
install:
  - pip install tox
# commands to run
script:
  - tox -e $TOX_ENV
after_success:
  - if [ "-x$TOX_ENV" = "xcoverage" ]; then coveralls; fi
